/**
 * Street data derived from the city's own records, not from memory.
 *
 * Source: every distinct `intersection_name` in the historical dispatch dataset
 * (`2zdj-bwza`), fetched 2026-09-18 — 6652 intersection strings covering
 * 2061 distinct street names. Regenerate with `bun run build:street-data`.
 */

/**
 * Street name → the suffix the city writes for it, where the records agree (>=80% of
 * mentions). Used to complete a name written without one: `IRVING` → `Irving St`.
 */
export const SF_STREET_SUFFIXES: Readonly<Record<string, string>> = {
  "09TH TI": "St",
  "10TH TI": "St",
  "11TH TI": "St",
  "12TH TI": "St",
  "13th": "St",
  "13TH TI": "St",
  "14TH TI": "St",
  "1st": "St",
  "31st": "Ave",
  "32nd": "Ave",
  "33rd": "Ave",
  "34th": "Ave",
  "35th": "Ave",
  "36th": "Ave",
  "37th": "Ave",
  "38th": "Ave",
  "39th": "Ave",
  "3rd": "St",
  "40th": "Ave",
  "41st": "Ave",
  "42nd": "Ave",
  "43rd": "Ave",
  "44th": "Ave",
  "45th": "Ave",
  "46th": "Ave",
  "47th": "Ave",
  "48th": "Ave",
  "ABBEY": "St",
  "ACADIA": "St",
  "ACEVEDO": "Ave",
  "ACME": "Aly",
  "ACORN": "Aly",
  "ACTON": "St",
  "ADA": "Ct",
  "ADAIR": "St",
  "ADDISON": "St",
  "ADELE": "Ct",
  "ADMIRAL": "Ave",
  "ADOLPH SUTRO": "Ct",
  "AERIAL": "Way",
  "AGNON": "Ave",
  "AGUA": "Way",
  "AHERN": "Way",
  "AL SCOMA": "Way",
  "ALABAMA": "St",
  "ALADDIN": "Ter",
  "ALAMEDA": "St",
  "ALANA": "Way",
  "ALBATROSS": "Ct",
  "ALBERTA": "St",
  "ALBION": "St",
  "ALDER": "St",
  "ALEMANY": "Blvd",
  "ALERT": "Aly",
  "ALHAMBRA": "St",
  "ALICE B TOKLAS": "Pl",
  "ALLEN": "St",
  "ALLISON": "St",
  "ALLSTON": "Way",
  "ALMA": "St",
  "ALMADEN": "Ct",
  "ALOHA": "Ave",
  "ALPHA": "St",
  "ALPINE": "Ter",
  "ALTA": "St",
  "ALTA MAR": "Way",
  "ALTA VISTA": "Ter",
  "ALTON": "Ave",
  "ALVARADO": "St",
  "ALVISO": "St",
  "AMADOR": "St",
  "AMAZON": "Ave",
  "AMBER": "Dr",
  "AMBROSE BIERCE": "St",
  "AMES": "St",
  "AMETHYST": "Way",
  "AMHERST": "St",
  "AMITY": "Aly",
  "ANDERSON": "St",
  "ANDOVER": "St",
  "ANGELOS": "Aly",
  "ANGLO": "Aly",
  "ANKENY": "St",
  "ANNAPOLIS": "Ter",
  "ANNIE": "St",
  "ANSON": "Pl",
  "ANTHONY": "St",
  "ANTONIO": "St",
  "ANZA": "St",
  "ANZAVISTA": "Ave",
  "APOLLO": "St",
  "APPLETON": "Ave",
  "APTOS": "Ave",
  "AQUAVISTA": "Way",
  "ARAGO": "St",
  "ARBALLO": "Dr",
  "ARBOL": "Ln",
  "ARBOR": "St",
  "ARCH": "St",
  "ARCO": "Way",
  "ARDENWOOD": "Way",
  "ARELIOUS WALKER": "Dr",
  "ARELLANO": "Ave",
  "ARGENT": "Aly",
  "ARGONAUT": "Ave",
  "ARGUELLO": "Blvd",
  "ARKANSAS": "St",
  "ARLETA": "Ave",
  "ARLINGTON": "St",
  "ARMISTEAD": "Rd",
  "ARMORY": "Dr",
  "ARMSTRONG": "Ave",
  "ARNOLD": "Ave",
  "ARROYO": "Way",
  "ARTHUR": "Ave",
  "ASH": "St",
  "ASHBURY": "St",
  "ASHTON": "Ave",
  "ASHWOOD": "Ln",
  "ASPEN": "Ct",
  "ATALAYA": "Ter",
  "ATHENS": "St",
  "ATTRIDGE": "Aly",
  "AUBURN": "St",
  "AUGUST": "Aly",
  "AUGUSTA": "St",
  "AUSTIN": "St",
  "AUTO": "Dr",
  "AUTOMOBILE": "Dr",
  "AVALON": "Ave",
  "AVERY": "St",
  "AVILA": "St",
  "AVOCA": "Aly",
  "AVOCET": "Way",
  "AZTEC": "St",
  "BACHE": "St",
  "BACON": "St",
  "BADEN": "St",
  "BADGER": "St",
  "BAKER": "St",
  "BALBOA": "St",
  "BALCETA": "Ave",
  "BALDWIN": "Ct",
  "BALHI": "Ct",
  "BALMY": "St",
  "BALTIMORE": "Way",
  "BANBURY": "Dr",
  "BANCROFT": "Ave",
  "BANKS": "St",
  "BANNAN": "Pl",
  "BANNEKER": "Way",
  "BANNOCK": "St",
  "BARCELONA": "Ave",
  "BARNEVELD": "Ave",
  "BARTLETT": "St",
  "BARTOL": "St",
  "BATTERY": "St",
  "BATTERY CHAMBERLIN": "Rd",
  "BATTERY CROSBY": "Rd",
  "BATTERY DYNAMITE": "Rd",
  "BATTERY SAFFORD": "Rd",
  "BAXTER": "Aly",
  "BAY": "St",
  "BAY SHORE": "Blvd",
  "BAY VIEW": "St",
  "BAYSIDE": "Dr",
  "BAYSIDE VILLAGE": "Pl",
  "BAYVIEW": "Cir",
  "BAYVIEW PARK": "Rd",
  "BAYWOOD": "Ct",
  "BEACH": "St",
  "BEACHMONT": "Dr",
  "BEACON": "St",
  "BEALE": "St",
  "BEATRICE": "Ln",
  "BEAUMONT": "Ave",
  "BEAVER": "St",
  "BECKETT": "St",
  "BEDFORD": "Pl",
  "BEEMAN": "Ln",
  "BEHR": "Ave",
  "BEIDEMAN": "St",
  "BELCHER": "St",
  "BELDEN": "St",
  "BELGRAVE": "Ave",
  "BELLA VISTA": "Way",
  "BELLAIR": "Pl",
  "BELLE": "Ave",
  "BELLES": "St",
  "BELMONT": "Ave",
  "BELVEDERE": "St",
  "BEMIS": "St",
  "BENGAL": "Aly",
  "BENNINGTON": "St",
  "BENTON": "Ave",
  "BERCUT ACCESS": "Rd",
  "BERGEN": "Aly",
  "BERKELEY": "Way",
  "BERKSHIRE": "Way",
  "BERNAL HEIGHTS": "Blvd",
  "BERNARD": "St",
  "BERNICE": "St",
  "BERNICE RODGERS": "Way",
  "BERRY": "St",
  "BERRY EXTENSION": "St",
  "BERTHA": "Ln",
  "BERTIE MINOR": "Ln",
  "BERTITA": "St",
  "BESSIE": "St",
  "BEULAH": "St",
  "BEVERLY": "St",
  "BIGLER": "Ave",
  "BIRCH": "St",
  "BIRCHWOOD": "Ct",
  "BIRD": "St",
  "BIRMINGHAM": "Rd",
  "BISHOP": "St",
  "BITTING": "Ave",
  "BLACK": "Pl",
  "BLACKSTONE": "Ct",
  "BLAIR": "Ter",
  "BLAIRWOOD": "Ln",
  "BLAKE": "St",
  "BLANCHE": "St",
  "BLANKEN": "Ave",
  "BLISS": "Rd",
  "BLUXOME": "St",
  "BLYTHDALE": "Ave",
  "BOARDMAN": "Pl",
  "BOB KAUFMAN": "Aly",
  "BOCANA": "St",
  "BONIFACIO": "St",
  "BONITA": "St",
  "BONNIE BRAE": "Ln",
  "BONVIEW": "St",
  "BORICA": "St",
  "BOSWORTH": "St",
  "BOUTWELL": "St",
  "BOWDOIN": "St",
  "BOWLEY": "St",
  "BOWLING GREEN": "Dr",
  "BOWMAN": "Ct",
  "BOYLSTON": "St",
  "BOYNTON": "Ct",
  "BRADFORD": "St",
  "BRADY": "St",
  "BRANNAN": "St",
  "BRANT": "Aly",
  "BRAZIL": "Ave",
  "BREEN": "Pl",
  "BRENTWOOD": "Ave",
  "BRET HARTE": "Ter",
  "BREWSTER": "St",
  "BRIDGEVIEW": "Dr",
  "BRIGHT": "St",
  "BRIGHTON": "Ave",
  "BRITTON": "St",
  "BROAD": "St",
  "BROADMOOR": "Dr",
  "BRODERICK": "St",
  "BROMLEY": "Pl",
  "BROMPTON": "Ave",
  "BRONTE": "St",
  "BROOK": "St",
  "BROOKDALE": "Ave",
  "BROOKHAVEN": "Ln",
  "BROOKLYN": "Pl",
  "BROOKS": "St",
  "BROSNAN": "St",
  "BROTHERHOOD": "Way",
  "BROWN": "St",
  "BRUCE": "Ave",
  "BRUMISS": "Ter",
  "BRUNSWICK": "St",
  "BRUSH": "Pl",
  "BRUSSELS": "St",
  "BRYANT": "St",
  "BUCARELI": "Dr",
  "BUCHANAN": "St",
  "BUCKINGHAM": "Way",
  "BURGOYNE": "St",
  "BURKE": "Ave",
  "BURLWOOD": "Dr",
  "BURNETT": "Ave",
  "BURNS": "Pl",
  "BURNSIDE": "Ave",
  "BURR": "Ave",
  "BURRITT": "St",
  "BURROWS": "St",
  "BUSH": "St",
  "BUTTE": "Pl",
  "BYRON": "Ct",
  "BYXBEE": "St",
  "CABRILLO": "St",
  "CADELL": "Pl",
  "CAINE": "Ave",
  "CALEDONIA": "St",
  "CALGARY": "St",
  "CALHOUN": "Ter",
  "CALIFORNIA": "St",
  "CAMBON": "Dr",
  "CAMBRIDGE": "St",
  "CAMELLIA": "Ave",
  "CAMEO": "Way",
  "CAMP": "St",
  "CAMPBELL": "Ave",
  "CAMPTON": "Pl",
  "CANDLESTICK COVE": "Way",
  "CANYON": "Dr",
  "CAPISTRANO": "Ave",
  "CAPITOL": "Ave",
  "CAPP": "St",
  "CAPRA": "Way",
  "CARD": "Aly",
  "CARDENAS": "Ave",
  "CARGO": "Way",
  "CARL": "St",
  "CARMEL": "St",
  "CARMELITA": "St",
  "CARNELIAN": "Way",
  "CAROLINA": "St",
  "CARR": "St",
  "CARRIE": "St",
  "CARRIZAL": "St",
  "CARROLL": "Ave",
  "CARSON": "St",
  "CARVER": "St",
  "CASA": "Way",
  "CASCADE": "Walk",
  "CASELLI": "Ave",
  "CASHMERE": "St",
  "CASITAS": "Ave",
  "CASSANDRA": "Ct",
  "CASTELO": "Ave",
  "CASTENADA": "Ave",
  "CASTILLO": "St",
  "CASTLE": "St",
  "CASTLE MANOR": "Ave",
  "CASTRO": "St",
  "CATALINA": "St",
  "CATHERINE": "Ct",
  "CAYUGA": "Ave",
  "CECILIA": "Ave",
  "CEDAR": "St",
  "CEDRO": "Ave",
  "CENTRAL": "Ave",
  "CENTRAL MAGAZINE": "Rd",
  "CENTURY": "Pl",
  "CERES": "St",
  "CERRITOS": "Ave",
  "CERVANTES": "Blvd",
  "CESAR CHAVEZ": "St",
  "CHABOT": "Ter",
  "CHAIN OF LAKES": "Dr",
  "CHANCERY": "Ln",
  "CHANNEL": "St",
  "CHAPMAN": "St",
  "CHARLES": "St",
  "CHARLES J BRENHAM": "Pl",
  "CHARLTON": "Ct",
  "CHARTER OAK": "Ave",
  "CHASE": "Ct",
  "CHATHAM": "Pl",
  "CHATTANOOGA": "St",
  "CHAVES": "Ave",
  "CHENERY": "St",
  "CHERRY": "St",
  "CHESLEY": "St",
  "CHESTER": "Ave",
  "CHESTNUT": "St",
  "CHICAGO": "Way",
  "CHILD": "St",
  "CHILTON": "Ave",
  "CHINA BASIN": "St",
  "CHINOOK": "Ct",
  "CHRISTOPHER": "Dr",
  "CHULA": "Ln",
  "CHUMASERO": "Dr",
  "CHURCH": "St",
  "CHURCH ACCESS": "Rd",
  "CIELITO": "Dr",
  "CIRCULAR": "Ave",
  "CITYVIEW": "Way",
  "CLAIRVIEW": "Ct",
  "CLARA": "St",
  "CLAREMONT": "Blvd",
  "CLARENCE": "Pl",
  "CLARENDON": "Ave",
  "CLARION": "Aly",
  "CLAY": "St",
  "CLAYTON": "St",
  "CLEARFIELD": "Dr",
  "CLEARVIEW": "Ct",
  "CLEARY": "Ct",
  "CLEMENT": "St",
  "CLEMENTINA": "St",
  "CLEO RAND": "Ave",
  "CLEVELAND": "St",
  "CLIFFORD": "Ter",
  "CLINTON": "Park",
  "CLIPPER": "St",
  "CLOUD": "Cir",
  "CLYDE": "St",
  "CODMAN": "Pl",
  "COLBY": "St",
  "COLE": "St",
  "COLEMAN": "St",
  "COLERIDGE": "St",
  "COLIN": "Pl",
  "COLIN P KELLY JR": "St",
  "COLLEEN": "Way",
  "COLLEGE": "Ave",
  "COLLINGWOOD": "St",
  "COLLINS": "St",
  "COLON": "Ave",
  "COLONIAL": "Way",
  "COLTON": "St",
  "COLUMBIA SQUARE": "St",
  "COLUMBUS": "Ave",
  "COLUSA": "Pl",
  "COMMER": "Ct",
  "COMMERCIAL": "St",
  "COMMONWEALTH": "Ave",
  "COMPTON": "Rd",
  "CONCORD": "St",
  "CONGDON": "St",
  "CONGO": "St",
  "CONKLING": "St",
  "CONNECTICUT": "St",
  "CONRAD": "St",
  "CONSERVATORY": "Dr",
  "CONSERVATORY ACCESS": "Rd",
  "CONSTANSO": "Way",
  "CONTINUUM": "Way",
  "COOK": "St",
  "COOPER": "Aly",
  "COPPER": "Aly",
  "CORA": "St",
  "CORALINO": "Ln",
  "CORBETT": "Ave",
  "CORBIN": "Pl",
  "CORDELIA": "St",
  "CORDOVA": "St",
  "CORINNE WOODS": "Way",
  "CORNWALL": "St",
  "CORONA": "St",
  "CORONADO": "St",
  "CORTES": "Ave",
  "CORTLAND": "Ave",
  "CORWIN": "St",
  "COSMO": "Pl",
  "COSO": "Ave",
  "COSTA": "St",
  "COTTAGE": "Row",
  "COTTER": "St",
  "COUNTRY CLUB": "Dr",
  "COWELL": "Pl",
  "COWLES": "St",
  "CRAGMONT": "Ave",
  "CRAGS": "Ct",
  "CRAIG": "Ln",
  "CRANE": "St",
  "CRANLEIGH": "Dr",
  "CRAUT": "St",
  "CRESCENT": "Ave",
  "CRESCIO": "Ct",
  "CRESPI": "Dr",
  "CRESTA VISTA": "Dr",
  "CRESTLAKE": "Dr",
  "CRESTLINE": "Dr",
  "CRESTMONT": "Dr",
  "CRISSY FIELD": "Ave",
  "CROAKER": "Ct",
  "CROOK": "St",
  "CROSS": "St",
  "CROSSOVER": "Dr",
  "CRYSTAL": "St",
  "CUBA": "Aly",
  "CUESTA": "Ct",
  "CULEBRA": "Ter",
  "CUMBERLAND": "St",
  "CUNNINGHAM": "Pl",
  "CURTIS": "St",
  "CUSHMAN": "St",
  "CUSTER": "Ave",
  "CUTLER": "Ave",
  "CUVIER": "St",
  "CYPRESS": "St",
  "CYRIL MAGNIN": "St",
  "CYRUS": "Pl",
  "DAGGETT": "St",
  "DAKOTA": "St",
  "DALEWOOD": "Way",
  "DANIEL BURNHAM": "Ct",
  "DANTON": "St",
  "DANVERS": "St",
  "DARIEN": "Way",
  "DARRELL": "Pl",
  "DARTMOUTH": "St",
  "DASHIELL HAMMETT": "St",
  "DAVIDSON": "Ave",
  "DAVIS": "St",
  "DAWNVIEW": "Way",
  "DAWSON": "Pl",
  "DAY": "St",
  "DE FOREST": "Way",
  "DE HARO": "St",
  "DE LONG": "St",
  "DE MONTFORT": "Ave",
  "DE SOTO": "St",
  "DEARBORN": "St",
  "DECKER": "Aly",
  "DEDMAN": "Ct",
  "DEEMS": "Rd",
  "DEHON": "St",
  "DEL MONTE": "St",
  "DEL SUR": "Ave",
  "DEL VALE": "Ave",
  "DELANCEY": "St",
  "DELANO": "Ave",
  "DELAWARE": "St",
  "DELGADO": "Pl",
  "DELLBROOK": "Ave",
  "DELMAR": "St",
  "DELTA": "St",
  "DEMING": "St",
  "DENSLOWE": "Dr",
  "DERBY": "St",
  "DESMOND": "St",
  "DETROIT": "St",
  "DEVONSHIRE": "Way",
  "DEWEY": "Blvd",
  "DIAMOND": "St",
  "DIAMOND COVE": "Ter",
  "DIAMOND HEIGHTS": "Blvd",
  "DIANA": "St",
  "DIAZ": "Ave",
  "DICHA": "Aly",
  "DICHIERA": "Ct",
  "DIGBY": "St",
  "DIRK DIRKSEN": "Pl",
  "DIVISADERO": "St",
  "DIVISION": "St",
  "DIXIE": "Aly",
  "DODGE": "St",
  "DOLORES": "St",
  "DOLPHIN": "Ct",
  "DON CHEE": "Way",
  "DONAHUE": "St",
  "DONNER": "Ave",
  "DORADO": "Ter",
  "DORANTES": "Ave",
  "DORCAS": "Way",
  "DORCHESTER": "Way",
  "DORE": "St",
  "DORIC": "Aly",
  "DORLAND": "St",
  "DORMITORY": "Rd",
  "DOUGLASS": "St",
  "DOW": "Pl",
  "DOWNEY": "St",
  "DR CARLTON B GOODLETT": "Pl",
  "DR TOM WADDELL": "Pl",
  "DRAKE": "St",
  "DRUMM": "St",
  "DRUMMOND": "Aly",
  "DUBLIN": "St",
  "DUBOCE": "Ave",
  "DUDLEY": "Rd",
  "DUKES": "Ct",
  "DUNCAN": "St",
  "DUNCOMBE": "Aly",
  "DUNSHEE": "St",
  "DUNSMUIR": "St",
  "DUTCH WINDMILL ACCESS": "Rd",
  "DWIGHT": "St",
  "EAGLE": "St",
  "EARL": "St",
  "EARL GAGE JR": "St",
  "EAST": "Rd",
  "EAST BEACH": "Rd",
  "EAST CRYSTAL COVE": "Ter",
  "EASTMAN": "St",
  "EASTWOOD": "Dr",
  "EATON": "Pl",
  "ECKER": "St",
  "EDDY": "St",
  "EDGAR": "Ave",
  "EDGARDO": "Pl",
  "EDGEHILL": "Way",
  "EDGEWOOD": "Ave",
  "EDIE": "Rd",
  "EDINBURGH": "St",
  "EDITH": "St",
  "EDNA": "St",
  "EDWARD": "St",
  "EGBERT": "Ave",
  "EL MIRASOL": "Pl",
  "EL SERENO": "Ct",
  "EL VERANO": "Way",
  "ELGIN": "Park",
  "ELIZABETH": "St",
  "ELK": "St",
  "ELLERT": "St",
  "ELLINGTON": "Ave",
  "ELLIOT": "St",
  "ELLIS": "St",
  "ELLSWORTH": "St",
  "ELM": "St",
  "ELMHURST": "Dr",
  "ELMIRA": "St",
  "ELMWOOD": "Way",
  "ELSIE": "St",
  "ELWOOD": "St",
  "EMERALD": "Ln",
  "EMERALD COVE": "Way",
  "EMERSON": "St",
  "EMERY": "Ln",
  "EMIL": "Ln",
  "EMMA": "St",
  "EMMETT": "Ct",
  "ENCANTO": "Ave",
  "ENCLINE": "Ct",
  "ENTERPRISE": "St",
  "ENTRADA": "Ct",
  "ERIE": "St",
  "ERKSON": "Ct",
  "ERVINE": "St",
  "ESCOLTA": "Way",
  "ESCONDIDO": "Ave",
  "ESMERALDA": "Ave",
  "ESPANOLA": "St",
  "ESQUINA": "Dr",
  "ESSEX": "St",
  "ESTERO": "Ave",
  "EUCALYPTUS": "Dr",
  "EUCLID": "Ave",
  "EUGENIA": "Ave",
  "EUREKA": "St",
  "EVANS": "Ave",
  "EVELYN": "Way",
  "EVERGLADE": "Dr",
  "EVERSON": "St",
  "EWER": "Pl",
  "EWING": "Ter",
  "EXCELSIOR": "Ave",
  "EXCHANGE": "Pl",
  "EXECUTIVE PARK": "Blvd",
  "EXETER": "St",
  "EXPOSITION": "Dr",
  "FAIR": "Ave",
  "FAIR OAKS": "St",
  "FAIRFAX": "Ave",
  "FAIRFIELD": "Way",
  "FAIRMOUNT": "St",
  "FAITH": "St",
  "FALLON": "Pl",
  "FALMOUTH": "St",
  "FANNING": "Way",
  "FARALLONES": "St",
  "FARGO": "Pl",
  "FARNSWORTH": "Ln",
  "FARNUM": "St",
  "FARRAGUT": "Ave",
  "FARVIEW": "Ct",
  "FAXON": "Ave",
  "FEDERAL": "St",
  "FELL": "St",
  "FELL ACCESS": "Rd",
  "FELLA": "Pl",
  "FELTON": "St",
  "FENTON": "Ln",
  "FERN": "St",
  "FERNANDEZ": "St",
  "FERNWOOD": "Dr",
  "FIELDING": "St",
  "FIFTH": "St",
  "FILBERT": "St",
  "FILLMORE": "St",
  "FINLEY": "Rd",
  "FIRST": "Dr",
  "FISHER": "Aly",
  "FITZGERALD": "Ave",
  "FLINT": "St",
  "FLOOD": "Ave",
  "FLORA": "St",
  "FLORENCE": "St",
  "FLORENTINE": "Ave",
  "FLORIDA": "St",
  "FLOUNDER": "Ct",
  "FLOURNOY": "St",
  "FOERSTER": "St",
  "FOLSOM": "St",
  "FONT": "Blvd",
  "FONTINELLA": "Ter",
  "FOOTE": "Ave",
  "FORD": "St",
  "FOREST HILL": "Path",
  "FOREST KNOLLS": "Dr",
  "FOREST SIDE": "Ave",
  "FOREST VIEW": "Dr",
  "FORT FUNSTON": "Rd",
  "FORTUNA": "Ave",
  "FOUNTAIN": "St",
  "FOWLER": "Ave",
  "FRANCE": "Ave",
  "FRANCIS": "St",
  "FRANCISCO": "St",
  "FRANCONIA": "St",
  "FRANK NORRIS": "St",
  "FRANKLIN": "St",
  "FRATESSA": "Ct",
  "FREDELA": "Ln",
  "FREDERICK": "St",
  "FREDSON": "Ct",
  "FREELON": "St",
  "FREMONT": "St",
  "FRENCH": "Ct",
  "FRESNO": "St",
  "FRIDA KAHLO": "Way",
  "FRIEDELL": "St",
  "FRIENDSHIP": "Ct",
  "FRONT": "St",
  "FUENTE": "Ave",
  "FULTON": "St",
  "FUNSTON": "Ave",
  "GABILAN": "Way",
  "GALEWOOD": "Cir",
  "GALILEE": "Ln",
  "GALINDO": "Ave",
  "GALLAGHER": "Ln",
  "GALVEZ": "Ave",
  "GAMBIER": "St",
  "GARCES": "Dr",
  "GARCIA": "Ave",
  "GARDEN": "St",
  "GARDENSIDE": "Dr",
  "GARFIELD": "St",
  "GARLINGTON": "Ct",
  "GARNETT": "Ter",
  "GARRISON": "Ave",
  "GATES": "St",
  "GATEVIEW": "Ave",
  "GATUN": "Aly",
  "GAVEN": "St",
  "GAVIOTA": "Way",
  "GEARY": "Blvd",
  "GELLERT": "Dr",
  "GENE FRIEND": "Way",
  "GENEBERN": "Way",
  "GENERAL KENNEDY": "Ave",
  "GENEVA": "Ave",
  "GENNESSEE": "St",
  "GENOA": "Pl",
  "GEORGE": "Ct",
  "GEORGIA": "Ln",
  "GERKE": "Aly",
  "GERMANIA": "St",
  "GETZ": "St",
  "GIANTS": "Dr",
  "GIBB": "St",
  "GIBSON": "Rd",
  "GILBERT": "St",
  "GILLETTE": "Ave",
  "GILMAN": "Ave",
  "GILROY": "St",
  "GIRARD": "St",
  "GLADEVIEW": "Way",
  "GLADSTONE": "Dr",
  "GLADYS": "St",
  "GLEN": "Ct",
  "GLENBROOK": "Ave",
  "GLENDALE": "St",
  "GLENHAVEN": "Ln",
  "GLENVIEW": "Dr",
  "GLOBE": "Aly",
  "GLORIA": "Ct",
  "GLOVER": "St",
  "GODEUS": "St",
  "GOETHE": "St",
  "GOETTINGEN": "St",
  "GOLD": "St",
  "GOLD MINE": "Dr",
  "GOLDBERG": "Ln",
  "GOLDEN": "Ct",
  "GOLDEN GATE": "Ave",
  "GOLDING": "Ln",
  "GOLF COURSE ACCESS": "Rd",
  "GONZALEZ": "Dr",
  "GORDON": "St",
  "GORGAS": "Ave",
  "GORHAM": "St",
  "GOUGH": "St",
  "GOULD": "St",
  "GRACE": "St",
  "GRAFTON": "Ave",
  "GRAHAM": "St",
  "GRANADA": "Ave",
  "GRAND VIEW": "Ave",
  "GRANT": "Ave",
  "GRANVILLE": "Way",
  "GRATTAN": "St",
  "GRAYSTONE": "Ter",
  "GREAT": "Hwy",
  "GREEN": "St",
  "GREENOUGH": "Ave",
  "GREENVIEW": "Ct",
  "GREENWICH": "St",
  "GREENWOOD": "Ave",
  "GRENARD": "Ter",
  "GRIFFITH": "St",
  "GRIJALVA": "Dr",
  "GROTE": "Pl",
  "GROVE": "St",
  "GUERRERO": "St",
  "GUTTENBERG": "St",
  "GUY": "Pl",
  "HABITAT": "Ter",
  "HAGIWARA TEA GARDEN": "Dr",
  "HAHN": "St",
  "HAIGHT": "St",
  "HALE": "St",
  "HALIBUT": "Ct",
  "HALLAM": "St",
  "HALLECK": "St",
  "HAMERTON": "Ave",
  "HAMILTON": "St",
  "HAMLIN": "St",
  "HAMPSHIRE": "St",
  "HANCOCK": "St",
  "HANGAH": "St",
  "HANOVER": "St",
  "HARBOR": "Rd",
  "HARDING": "Rd",
  "HARKNESS": "Ave",
  "HARLAN": "Pl",
  "HARLEM": "Aly",
  "HARLOW": "St",
  "HARMONIA": "St",
  "HARNEY": "Way",
  "HAROLD": "Ave",
  "HARPER": "St",
  "HARRIET": "St",
  "HARRINGTON": "St",
  "HARRIS": "Pl",
  "HARRISON": "St",
  "HARRY": "St",
  "HARTFORD": "St",
  "HARVARD": "St",
  "HASTINGS": "Ter",
  "HATTIE": "St",
  "HAVELOCK": "St",
  "HAVENS": "St",
  "HAVENSIDE": "Dr",
  "HAWES": "St",
  "HAWKINS": "Ln",
  "HAWTHORNE": "St",
  "HAYES": "St",
  "HAYS": "St",
  "HAZELWOOD": "Ave",
  "HEAD": "St",
  "HEARST": "Ave",
  "HEATHER": "Ave",
  "HELEN": "St",
  "HEMLOCK": "St",
  "HEMWAY": "Ter",
  "HENRY": "St",
  "HENRY ADAMS": "St",
  "HERITAGE": "Ln",
  "HERMANN": "St",
  "HERNANDEZ": "Ave",
  "HESTER": "Ave",
  "HEYMAN": "Ave",
  "HICKORY": "St",
  "HIDALGO": "Ter",
  "HIGH": "St",
  "HIGHLAND": "Ave",
  "HIGUERA": "Ave",
  "HILIRITAS": "Ave",
  "HILL": "St",
  "HILL POINT": "Ave",
  "HILLCREST": "Ct",
  "HILLVIEW": "Ct",
  "HILLWAY": "Ave",
  "HIMMELMANN": "Pl",
  "HOBART": "Aly",
  "HODGES": "Aly",
  "HOFF": "St",
  "HOFFMAN": "Ave",
  "HOLLADAY": "Ave",
  "HOLLIS": "St",
  "HOLLISTER": "Ave",
  "HOLLOWAY": "Ave",
  "HOLLY PARK": "Cir",
  "HOLLYWOOD": "Ct",
  "HOLYOKE": "St",
  "HOMESTEAD": "St",
  "HOMEWOOD": "Ct",
  "HOOKER": "Aly",
  "HOOPER": "St",
  "HOPKINS": "Ave",
  "HORACE": "St",
  "HOTALING": "Pl",
  "HOUSTON": "St",
  "HOWARD": "St",
  "HOWTH": "St",
  "HUBBELL": "St",
  "HUDSON": "Ave",
  "HUGO": "St",
  "HULBERT": "Aly",
  "HUMBOLDT": "St",
  "HUNTERS POINT": "Blvd",
  "HUNTINGTON": "Dr",
  "HURON": "Ave",
  "HYDE": "St",
  "ICEHOUSE": "Aly",
  "IDORA": "Ave",
  "IGNACIO": "Ave",
  "ILLINOIS": "St",
  "ILS": "Ln",
  "IMPERIAL": "Aly",
  "INA": "Ct",
  "INCA": "Ln",
  "INDIANA": "St",
  "INDUSTRIAL": "St",
  "INFANTRY": "Ter",
  "INGALLS": "St",
  "INGERSON": "Ave",
  "INGLESIDE": "Path",
  "INNES": "Ave",
  "INVERNESS": "Dr",
  "IRIS": "Ave",
  "IRON": "Aly",
  "IRONWOOD": "Way",
  "IRVING": "St",
  "IRWIN": "St",
  "ISADORA DUNCAN": "Ln",
  "ISIS": "St",
  "ISOLA": "Way",
  "ISSLEIB": "Ave",
  "ITALY": "Ave",
  "IVY": "St",
  "JACK BALESTRERI": "Way",
  "JACK KEROUAC": "Aly",
  "JACK LONDON": "Aly",
  "JACK MICHELINE": "Aly",
  "JACKSON": "St",
  "JADE": "Pl",
  "JAKEY": "Ct",
  "JAMESTOWN": "Ave",
  "JANSEN": "St",
  "JARBOE": "Ave",
  "JASON": "Ct",
  "JASPER": "Pl",
  "JAUSS": "St",
  "JAVA": "St",
  "JEAN": "Way",
  "JEFF ADACHI": "Way",
  "JEFFERSON": "St",
  "JENNINGS": "St",
  "JEROME": "Aly",
  "JERROLD": "Ave",
  "JERSEY": "St",
  "JESSIE": "St",
  "JESSIE EAST": "St",
  "JESSIE WEST": "St",
  "JOHN": "St",
  "JOHN F KENNEDY": "Dr",
  "JOHN F SHELLEY": "Dr",
  "JOHN MAHER": "St",
  "JOHN MUIR": "Dr",
  "JOHNSTONE": "Dr",
  "JOICE": "St",
  "JONES": "St",
  "JOOST": "Ave",
  "JORDAN": "Ave",
  "JOSE SARRIA": "Ct",
  "JOSEPHA": "Ave",
  "JOSIAH": "Ave",
  "JOY": "St",
  "JUAN BAUTISTA": "Cir",
  "JUANITA": "Way",
  "JUDAH": "St",
  "JUDSON": "Ave",
  "JULES": "Ave",
  "JULIA": "St",
  "JULIAN": "Ave",
  "JULIUS": "St",
  "JUNIOR": "Ter",
  "JUNIPER": "St",
  "JUNIPERO SERRA": "Blvd",
  "JURI": "St",
  "JUSTIN": "Dr",
  "KALMANOVITZ": "St",
  "KAMILLE": "Ct",
  "KANSAS": "St",
  "KAPLAN": "Ln",
  "KAREN": "Ct",
  "KATE": "St",
  "KEARNY": "St",
  "KEITH": "St",
  "KELLOCH": "Ave",
  "KEMPTON": "Ave",
  "KENDALL": "Dr",
  "KENNEDY": "Pl",
  "KENNETH REXROTH": "Pl",
  "KENNY": "Aly",
  "KENSINGTON": "Way",
  "KENT": "St",
  "KENWOOD": "Way",
  "KEPPLER": "Ct",
  "KERN": "St",
  "KEY": "Ave",
  "KEYSTONE": "Way",
  "KEZAR": "Dr",
  "KIMBALL": "Pl",
  "KING": "St",
  "KINGSTON": "St",
  "KINZEY": "St",
  "KIRKHAM": "St",
  "KIRKWOOD": "Ave",
  "KISKA": "Rd",
  "KISSLING": "St",
  "KITTREDGE": "Ter",
  "KNOLLVIEW": "Way",
  "KNOTT": "Ct",
  "KOBBE": "Ave",
  "KOHLER": "Pl",
  "KORET": "Way",
  "KRAMER": "Pl",
  "KRAUSGRILL": "Pl",
  "KRONQUIST": "Ct",
  "LA BICA": "Way",
  "LA FERRERA": "Ter",
  "LA GRANDE": "Ave",
  "LA SALLE": "Ave",
  "LAFAYETTE": "St",
  "LAGUNA": "St",
  "LAGUNA HONDA": "Blvd",
  "LAGUNITAS": "Dr",
  "LAIDLEY": "St",
  "LAKE": "St",
  "LAKE FOREST": "Ct",
  "LAKE MERCED": "Blvd",
  "LAKE MERCED HILL": "St",
  "LAKESHORE": "Dr",
  "LAKEVIEW": "Ave",
  "LAKEWOOD": "Ave",
  "LAMARTINE": "St",
  "LAMSON": "Ln",
  "LANCASTER": "Ln",
  "LANDERS": "St",
  "LANE": "St",
  "LANGDON": "Ct",
  "LANGTON": "St",
  "LANSDALE": "Ave",
  "LANSING": "St",
  "LAPHAM": "Way",
  "LAPIDGE": "St",
  "LAPU-LAPU": "St",
  "LARCH": "St",
  "LARKIN": "St",
  "LAS VILLAS": "Ct",
  "LASSEN": "Aly",
  "LATHROP": "Ave",
  "LATONA": "St",
  "LAURA": "St",
  "LAUREL": "St",
  "LAUREN": "Ct",
  "LAUSSAT": "St",
  "LAWRENCE": "Ave",
  "LAWTON": "St",
  "LE CONTE": "Ave",
  "LEAVENWORTH": "St",
  "LEDYARD": "St",
  "LEE": "Ave",
  "LEESE": "St",
  "LEGION": "Ct",
  "LEGION OF HONOR": "Dr",
  "LEIDESDORFF": "St",
  "LELAND": "Ave",
  "LENDRUM": "Ct",
  "LENOX": "Way",
  "LEO": "St",
  "LEONA": "Ter",
  "LEROY": "Pl",
  "LESSING": "St",
  "LESTER": "Ct",
  "LEVANT": "St",
  "LEXINGTON": "St",
  "LIBERTY": "St",
  "LICK": "Pl",
  "LIEBIG": "St",
  "LIGGETT": "Ave",
  "LILAC": "St",
  "LILLIAN": "St",
  "LILY": "St",
  "LINARES": "Ave",
  "LINDA": "St",
  "LINDA VISTA": "Stps",
  "LINDEN": "St",
  "LINDSAY": "Cir",
  "LIPPARD": "Ave",
  "LISBON": "St",
  "LITTLEFIELD": "Ter",
  "LLOYD": "St",
  "LOBOS": "St",
  "LOCKSLEY": "Ave",
  "LOCUST": "St",
  "LOEHR": "St",
  "LOIS": "Ln",
  "LOMA VISTA": "Ter",
  "LOMBARD": "St",
  "LOMITA": "Ave",
  "LONDON": "St",
  "LONE MOUNTAIN": "Ter",
  "LONG": "Ave",
  "LONG BRIDGE": "St",
  "LOOMIS": "St",
  "LOPEZ": "Ave",
  "LORI": "Ln",
  "LOS PALMOS": "Dr",
  "LOTTIE BENNETT": "Ln",
  "LOUISBURG": "St",
  "LOUISIANA": "St",
  "LOWELL": "St",
  "LOWER": "Ter",
  "LOWER FORT MASON": "St",
  "LOYOLA": "Ter",
  "LUCERNE": "St",
  "LUCKY": "St",
  "LUCY": "St",
  "LUDLOW": "Aly",
  "LULU": "Aly",
  "LUNDEEN": "St",
  "LUNDYS": "Ln",
  "LUPINE": "Ave",
  "LURLINE": "St",
  "LURMONT": "Ter",
  "LUSK": "St",
  "LYDIA": "Ave",
  "LYELL": "St",
  "LYNCH": "St",
  "LYNDHURST": "Dr",
  "LYON": "St",
  "LYSETTE": "St",
  "MABEL": "Aly",
  "MABINI": "St",
  "MABREY": "Ct",
  "MACARTHUR": "Ave",
  "MACEDONIA": "St",
  "MACONDRAY": "Ln",
  "MADDUX": "Ave",
  "MADERA": "St",
  "MADISON": "St",
  "MADRID": "St",
  "MADRONE": "Ave",
  "MAGELLAN": "Ave",
  "MAGNOLIA": "St",
  "MAIDEN": "Ln",
  "MAIN": "St",
  "MAJESTIC": "Ave",
  "MALLORCA": "Way",
  "MALOSI": "St",
  "MALTA": "Dr",
  "MALVINA": "Pl",
  "MANCHESTER": "St",
  "MANDALAY": "Ln",
  "MANGELS": "Ave",
  "MANOR": "Dr",
  "MANSELL": "St",
  "MANSFIELD": "St",
  "MANZANITA": "Ave",
  "MAPLE": "St",
  "MARCELA": "Ave",
  "MARCY": "Pl",
  "MARENGO": "St",
  "MARGARET": "Ave",
  "MARGRAVE": "Pl",
  "MARIETTA": "Dr",
  "MARIN": "St",
  "MARINA": "Blvd",
  "MARINA GREEN": "Dr",
  "MARINE": "Dr",
  "MARINER": "Dr",
  "MARION": "Pl",
  "MARIPOSA": "St",
  "MARK": "Ln",
  "MARK TWAIN": "Pl",
  "MARKET": "St",
  "MARNE": "Ave",
  "MARS": "St",
  "MARSILY": "St",
  "MARSTON": "Ave",
  "MARTHA": "Ave",
  "MARTIN": "Ave",
  "MARTIN LUTHER KING JR": "Dr",
  "MARVEL": "Ct",
  "MARVIEW": "Way",
  "MARY": "St",
  "MARY TERESA": "St",
  "MARYLAND": "St",
  "MASON": "St",
  "MASONIC": "Ave",
  "MASSASOIT": "St",
  "MATEO": "St",
  "MATTHEW": "Ct",
  "MAXWELL": "Ct",
  "MAYFAIR": "Dr",
  "MAYFLOWER": "St",
  "MAYNARD": "St",
  "MAYWOOD": "Dr",
  "MCALLISTER": "St",
  "MCCARTHY": "Ave",
  "MCCOPPIN": "St",
  "MCCORMICK": "St",
  "MCDOWELL": "Ave",
  "MCKINNON": "Ave",
  "MCLAREN": "Ave",
  "MCLAREN LODGE ACCESS": "Rd",
  "MCLEA": "Ct",
  "MEACHAM": "Pl",
  "MEADE": "Ave",
  "MEADOWBROOK": "Dr",
  "MEDA": "Ave",
  "MEDAU": "Pl",
  "MEDICAL CENTER": "Way",
  "MEGAN": "Dr",
  "MELBA": "Ave",
  "MELRA": "Ct",
  "MELROSE": "Ave",
  "MENDELL": "St",
  "MENDOSA": "Ave",
  "MERCATO": "Ct",
  "MERCED": "Ave",
  "MERCEDES": "Way",
  "MERCHANT": "St",
  "MERCURY": "St",
  "MERLIN": "St",
  "MERRIE": "Way",
  "MERRILL": "St",
  "MERRIMAC": "St",
  "MERRITT": "St",
  "MERSEY": "St",
  "MESA": "Ave",
  "METSON": "Rd",
  "MICHIGAN": "St",
  "MIDCREST": "Way",
  "MIDDLE POINT": "Rd",
  "MIDDLE WEST": "Dr",
  "MIDDLEFIELD": "Dr",
  "MIDWAY": "St",
  "MIGUEL": "St",
  "MILAN": "Ter",
  "MILES": "St",
  "MILEY": "St",
  "MILL": "St",
  "MILLWRIGHT COTTAGE ACCESS": "Rd",
  "MILTON": "St",
  "MINERVA": "St",
  "MINNA": "St",
  "MINNESOTA": "St",
  "MIRABEL": "Ave",
  "MIRALOMA": "Dr",
  "MIRAMAR": "Ave",
  "MISSION": "St",
  "MISSION ROCK": "St",
  "MISSISSIPPI": "St",
  "MISSOURI": "St",
  "MISTRAL": "St",
  "MIZPAH": "St",
  "MODOC": "Ave",
  "MOFFITT": "St",
  "MOJAVE": "St",
  "MOLIMO": "Dr",
  "MONCADA": "Way",
  "MONETA": "Way",
  "MONO": "St",
  "MONTAGUE": "Pl",
  "MONTALVO": "Ave",
  "MONTANA": "St",
  "MONTCALM": "St",
  "MONTCLAIR": "Ter",
  "MONTECITO": "Ave",
  "MONTEREY": "Blvd",
  "MONTEZUMA": "St",
  "MONTGOMERY": "St",
  "MONTICELLO": "St",
  "MONUMENT": "Way",
  "MOORE": "Pl",
  "MORAGA": "St",
  "MORELAND": "St",
  "MORGAN": "Aly",
  "MORNINGSIDE": "Dr",
  "MORRELL": "Pl",
  "MORRIS": "St",
  "MORSE": "St",
  "MORTON": "St",
  "MOSCOW": "St",
  "MOSS": "St",
  "MOULTON": "St",
  "MOULTRIE": "St",
  "MOUNT": "Ln",
  "MOUNT VERNON": "Ave",
  "MOUNTAIN SPRING": "Ave",
  "MOUNTVIEW": "Ct",
  "MRS. JACKSON": "Way",
  "MULFORD": "Aly",
  "MULLEN": "Ave",
  "MUNICH": "St",
  "MURRAY": "St",
  "MUSIC CONCOURSE": "Dr",
  "MUSIC CONCOURSE ACCESS": "Rd",
  "MYRA": "Way",
  "MYRTLE": "St",
  "NADELL": "Ct",
  "NAGLEE": "Ave",
  "NAHUA": "Ave",
  "NANCY PELOSI": "Dr",
  "NANTUCKET": "Ave",
  "NAPIER": "Ln",
  "NAPLES": "St",
  "NATICK": "St",
  "NATOMA": "St",
  "NAUTILUS": "Dr",
  "NAVAJO": "Ave",
  "NAVY": "Rd",
  "NAYLOR": "St",
  "NEBRASKA": "St",
  "NELLIE": "St",
  "NELSON RISING": "Ln",
  "NEPTUNE": "St",
  "NEVADA": "St",
  "NEW MONTGOMERY": "St",
  "NEWBURG": "St",
  "NEWCOMB": "Ave",
  "NEWELL": "St",
  "NEWHALL": "St",
  "NEWMAN": "St",
  "NEWTON": "St",
  "NEY": "St",
  "NIAGARA": "Ave",
  "NIANTIC": "Ave",
  "NIBBI": "Ct",
  "NIDO": "Ave",
  "NOB HILL": "Pl",
  "NOBLES": "Aly",
  "NOE": "St",
  "NORDHOFF": "St",
  "NORIEGA": "St",
  "NORMANDIE": "Ter",
  "NORTH": "Dr",
  "NORTH 15TH": "Ave",
  "NORTH POINT": "St",
  "NORTH VIEW": "Ct",
  "NORTHGATE": "Dr",
  "NORTHPOINT": "Dr",
  "NORTHRIDGE": "Rd",
  "NORTHWOOD": "Dr",
  "NORTON": "St",
  "NORWICH": "St",
  "NUEVA": "Ave",
  "OAK": "St",
  "OAK ACCESS": "Rd",
  "OAK GROVE": "St",
  "OAK PARK": "Dr",
  "OAKDALE": "Ave",
  "OAKHURST": "Ln",
  "OAKWOOD": "St",
  "OCEAN": "Ave",
  "OCEANVIEW": "Ter",
  "OCTAVIA": "St",
  "OFARRELL": "St",
  "OGDEN": "Ave",
  "OHLONE": "Way",
  "OLD CHINATOWN": "Ln",
  "OLD MASON": "St",
  "OLIVE": "St",
  "OLIVER": "St",
  "OLMSTEAD": "St",
  "OLYMPIA": "Way",
  "OLYMPIC COUNTRY CLUB": "Rd",
  "OMAR": "Way",
  "ONEIDA": "Ave",
  "ONIQUE": "Ln",
  "ONONDAGA": "Ave",
  "OPAL": "Pl",
  "OPALO": "Ln",
  "OPHIR": "Aly",
  "ORA": "Way",
  "ORANGE": "Aly",
  "ORBEN": "Pl",
  "ORDWAY": "St",
  "OREILLY": "Ave",
  "ORIOLE": "Way",
  "ORIZABA": "Ave",
  "ORSI": "Cir",
  "ORTEGA": "St",
  "OSAGE": "Aly",
  "OSCEOLA": "Ln",
  "OSHAUGHNESSY": "Blvd",
  "OTEGA": "Ave",
  "OTIS": "St",
  "OTSEGO": "Ave",
  "OTTAWA": "Ave",
  "OVERLOOK": "Dr",
  "OWEN": "St",
  "OWENS": "St",
  "OXFORD": "St",
  "OZBOURN": "Ct",
  "PACHECO": "St",
  "PACIFIC": "Ave",
  "PAGE": "St",
  "PAGODA": "Pl",
  "PALMETTO": "Ave",
  "PALO ALTO": "Ave",
  "PALOMA": "Ave",
  "PALOS": "Pl",
  "PALOU": "Ave",
  "PANAMA": "St",
  "PANORAMA": "Dr",
  "PARADISE": "Ave",
  "PARAISO": "Pl",
  "PARAMOUNT": "Ter",
  "PARIS": "St",
  "PARK HILL": "Ave",
  "PARK PRESIDIO": "Blvd",
  "PARK PRESIDIO BYPASS": "Dr",
  "PARKER": "Ave",
  "PARKHURST": "Aly",
  "PARKRIDGE": "Dr",
  "PARNASSUS": "Ave",
  "PARQUE": "Dr",
  "PARSONS": "St",
  "PASADENA": "St",
  "PATTON": "St",
  "PAUL": "Ave",
  "PAULDING": "St",
  "PAYSON": "St",
  "PEABODY": "St",
  "PEARL": "St",
  "PELICAN COVE": "Ter",
  "PELTON": "Pl",
  "PEMBERTON": "Pl",
  "PENINSULA": "Ave",
  "PENNSYLVANIA": "Ave",
  "PENNY": "Ln",
  "PERALTA": "Ave",
  "PEREGO": "Ter",
  "PERINE": "Pl",
  "PERRY": "St",
  "PERSHING": "Dr",
  "PERSIA": "Ave",
  "PERU": "Ave",
  "PETER YORKE": "Way",
  "PETERS": "Ave",
  "PETRARCH": "Pl",
  "PFEIFFER": "St",
  "PHELPS": "St",
  "PHOENIX": "Ter",
  "PICO": "Ave",
  "PIEDMONT": "St",
  "PIERCE": "St",
  "PILGRIM": "Ave",
  "PINAR": "Ln",
  "PINE": "St",
  "PINEHURST": "Way",
  "PINK": "Aly",
  "PINTO": "Ave",
  "PIOCHE": "St",
  "PIXLEY": "St",
  "PIZARRO": "Way",
  "PLAZA": "St",
  "PLEASANT": "St",
  "PLUM": "St",
  "PLYMOUTH": "Ave",
  "POINT LOBOS": "Ave",
  "POLARIS": "Way",
  "POLK": "St",
  "POLLARD": "Pl",
  "POMONA": "St",
  "POND": "St",
  "PONTIAC": "St",
  "POPE": "St",
  "POPLAR": "St",
  "POPPY": "Ln",
  "PORTER": "St",
  "PORTOLA": "Dr",
  "POST": "St",
  "POTOMAC": "St",
  "POTRERO": "Ave",
  "POWELL": "St",
  "POWERS": "Ave",
  "POWHATTAN": "Ave",
  "PRADO": "St",
  "PRAGUE": "St",
  "PRATT": "Pl",
  "PRECITA": "Ave",
  "PRENTISS": "St",
  "PRESCOTT": "Ct",
  "PRETOR": "Way",
  "PRIEST": "St",
  "PRINCETON": "St",
  "PROGRESS": "St",
  "PROSPECT": "Ave",
  "PROSPER": "St",
  "PUBLIC": "Park",
  "PUEBLO": "St",
  "PUTNAM": "St",
  "QUANE": "St",
  "QUARRY": "Rd",
  "QUARTZ": "Way",
  "QUESADA": "Ave",
  "QUICKSTEP": "Ln",
  "QUINT": "St",
  "QUINTARA": "St",
  "RACCOON": "Dr",
  "RACINE": "Ln",
  "RADIO": "Ter",
  "RAE": "Ave",
  "RALEIGH": "St",
  "RAMONA": "Ave",
  "RAMSEL": "Ct",
  "RAMSELL": "St",
  "RANDALL": "St",
  "RANDOLPH": "St",
  "RANKIN": "St",
  "RAUSCH": "St",
  "RAVENWOOD": "Dr",
  "RAYBURN": "St",
  "RAYCLIFF": "Ter",
  "RAYMOND": "Ave",
  "REARDON": "Rd",
  "REBECCA": "Ln",
  "RECYCLE": "Rd",
  "RECYCLING CENTER ACCESS": "Rd",
  "RED LEAF": "Ct",
  "RED ROCK": "Way",
  "REDDY": "St",
  "REDFIELD": "Aly",
  "REDONDO": "St",
  "REDWOOD": "St",
  "REED": "St",
  "REEVES": "Ct",
  "REGENT": "St",
  "RENO": "Pl",
  "REPOSA": "Way",
  "RESERVOIR": "St",
  "RESTANI": "Way",
  "RETIRO": "Way",
  "REUEL": "Ct",
  "REVERE": "Ave",
  "REX": "Ave",
  "REY": "St",
  "RHINE": "St",
  "RHODE ISLAND": "St",
  "RICE": "St",
  "RICHARDS": "Cir",
  "RICHARDSON": "Ave",
  "RICHLAND": "Ave",
  "RICO": "Way",
  "RIDGEWOOD": "Ave",
  "RINCON": "St",
  "RINGOLD": "St",
  "RIO": "Ct",
  "RIO VERDE": "St",
  "RIPLEY": "St",
  "RITCH": "St",
  "RIVAS": "Ave",
  "RIVERA": "St",
  "RIVERTON": "Dr",
  "RIVOLI": "St",
  "RIZAL": "St",
  "ROACH": "St",
  "ROANOKE": "St",
  "ROBBLEE": "Ave",
  "ROBINHOOD": "Dr",
  "ROCK": "Aly",
  "ROCKAWAY": "Ave",
  "ROCKDALE": "Dr",
  "ROCKLAND": "St",
  "ROCKRIDGE": "Dr",
  "ROCKWOOD": "Ct",
  "ROD": "Rd",
  "RODRIGUEZ": "St",
  "ROEMER": "Way",
  "ROLPH": "St",
  "ROMAIN": "St",
  "ROME": "St",
  "ROMOLO": "St",
  "ROOSEVELT": "Way",
  "ROSA PARKS": "Ln",
  "ROSCOE": "St",
  "ROSE": "St",
  "ROSELLA": "Ct",
  "ROSELYN": "Ter",
  "ROSEMARY": "Ct",
  "ROSEMONT": "Pl",
  "ROSENKRANZ": "St",
  "ROSEWOOD": "Dr",
  "ROSIE LEE": "Ln",
  "ROSS": "Aly",
  "ROSSI": "Ave",
  "ROSSMOOR": "Dr",
  "ROTTECK": "St",
  "ROUSSEAU": "St",
  "ROYAL": "Ln",
  "RUDDEN": "Ave",
  "RUSS": "St",
  "RUSSELL": "St",
  "RUSSIA": "Ave",
  "RUTH": "St",
  "RUTLAND": "St",
  "RUTLEDGE": "St",
  "SABIN": "Pl",
  "SACRAMENTO": "St",
  "SADDLEBACK": "Dr",
  "SADOWA": "St",
  "SAFIRA": "Ln",
  "SAGAMORE": "St",
  "SAINT CHARLES": "Ave",
  "SAINT ELMO": "Way",
  "SAINT FRANCIS": "Blvd",
  "SAINT GERMAIN": "Ave",
  "SAINT JOSEPHS": "Ave",
  "SAINT LOUIS": "Aly",
  "SAINT MARYS": "Ave",
  "SAL": "St",
  "SALA": "Ter",
  "SALINAS": "Ave",
  "SALMON": "St",
  "SAMOSET": "St",
  "SAN ALESO": "Ave",
  "SAN ANDREAS": "Way",
  "SAN ANSELMO": "Ave",
  "SAN ANTONIO": "Pl",
  "SAN BENITO": "Way",
  "SAN BRUNO": "Ave",
  "SAN BUENAVENTURA": "Way",
  "SAN CARLOS": "St",
  "SAN FELIPE": "Ave",
  "SAN FERNANDO": "Way",
  "SAN FRANCISCO GOLF CLUB": "Rd",
  "SAN GABRIEL": "Ave",
  "SAN JACINTO": "Way",
  "SAN JOSE": "Ave",
  "SAN JUAN": "Ave",
  "SAN LEANDRO": "Way",
  "SAN LORENZO": "Way",
  "SAN MARCOS": "Ave",
  "SAN MIGUEL": "St",
  "SAN PABLO": "Ave",
  "SAN RAFAEL": "Way",
  "SAN RAMON": "Way",
  "SANCHEZ": "St",
  "SANDPIPER COVE": "Way",
  "SANSOME": "St",
  "SANTA ANA": "Ave",
  "SANTA BARBARA": "Ave",
  "SANTA CLARA": "Ave",
  "SANTA CRUZ": "Ave",
  "SANTA FE": "Ave",
  "SANTA MARINA": "St",
  "SANTA MONICA": "Way",
  "SANTA PAULA": "Ave",
  "SANTA RITA": "Ave",
  "SANTA ROSA": "Ave",
  "SANTA YNEZ": "Ave",
  "SANTA YSABEL": "Ave",
  "SANTIAGO": "St",
  "SANTOS": "St",
  "SARGENT": "St",
  "SATURN": "St",
  "SAWYER": "St",
  "SCENIC": "Way",
  "SCHOOL": "Aly",
  "SCHWERIN": "St",
  "SCIENCE": "Cir",
  "SCOTIA": "Ave",
  "SCOTLAND": "St",
  "SCOTT": "St",
  "SEA VIEW": "Ter",
  "SEACLIFF": "Ave",
  "SEAL ROCK": "Dr",
  "SEARS": "St",
  "SECOND": "Dr",
  "SECURITY PACIFIC": "Pl",
  "SELBY": "St",
  "SELMA": "Way",
  "SEMINOLE": "Ave",
  "SENECA": "Ave",
  "SEQUOIA": "Way",
  "SERGEANT JOHN V YOUNG": "St",
  "SERRANO": "Dr",
  "SERVICE": "St",
  "SEVERN": "St",
  "SEVILLE": "St",
  "SEWARD": "St",
  "SEYMOUR": "St",
  "SHAFTER": "Ave",
  "SHAKESPEARE": "St",
  "SHANNON": "St",
  "SHARON": "St",
  "SHARP": "Pl",
  "SHAW": "Aly",
  "SHAWNEE": "Ave",
  "SHEPHARD": "Pl",
  "SHERMAN": "St",
  "SHIELDS": "St",
  "SHIPLEY": "St",
  "SHORE VIEW": "Ave",
  "SHORT": "St",
  "SHOTWELL": "St",
  "SHOUP": "Ave",
  "SHRADER": "St",
  "SIBLEY": "Rd",
  "SICKLES": "Ave",
  "SIERRA": "St",
  "SILLIMAN": "St",
  "SILVER": "Ave",
  "SILVERVIEW": "Dr",
  "SIXTH": "St",
  "SKYLINE": "Blvd",
  "SKYVIEW": "Way",
  "SLOAT": "Blvd",
  "SOLA": "Ave",
  "SOMERSET": "St",
  "SONOMA": "St",
  "SOTELO": "Ave",
  "SOUTH": "Park",
  "SOUTH HILL": "Blvd",
  "SOUTH VAN NESS": "Ave",
  "SOUTHARD": "Pl",
  "SOUTHERN HEIGHTS": "Ave",
  "SOUTHWOOD": "Dr",
  "SPARROW": "St",
  "SPARTA": "St",
  "SPEAR": "St",
  "SPENCER": "St",
  "SPOFFORD": "St",
  "SPRECKELS LAKE": "Dr",
  "SPRING": "St",
  "SPRINGFIELD": "Dr",
  "SPROULE": "Ln",
  "SPRUCE": "St",
  "STANFORD": "St",
  "STANFORD HEIGHTS": "Ave",
  "STANLEY": "St",
  "STANTON": "St",
  "STANYAN": "St",
  "STAPLES": "Ave",
  "STARK": "St",
  "STARR KING": "Way",
  "STARVIEW": "Way",
  "STATE": "Dr",
  "STATES": "St",
  "STEINER": "St",
  "STERLING": "St",
  "STERN GROVE": "Ct",
  "STEUART": "St",
  "STEVELOE": "Pl",
  "STEVENSON": "St",
  "STILL": "St",
  "STILLINGS": "Ave",
  "STILLMAN": "St",
  "STILWELL": "Rd",
  "STOCKTON": "St",
  "STONE": "St",
  "STONECREST": "Dr",
  "STONEMAN": "St",
  "STONERIDGE": "Ln",
  "STONEYBROOK": "Ave",
  "STONEYFORD": "Ave",
  "STOREY": "Ave",
  "STORRIE": "St",
  "STOW LAKE": "Dr",
  "STRATFORD": "Dr",
  "STRIPED BASS": "St",
  "STURGEON": "St",
  "SUMMIT": "St",
  "SUMNER": "St",
  "SUNBEAM": "Ln",
  "SUNGLOW": "Ln",
  "SUNNYDALE": "Ave",
  "SUNNYSIDE": "Ter",
  "SUNRISE": "Way",
  "SUNSET": "Blvd",
  "SUNVIEW": "Dr",
  "SURREY": "St",
  "SUSSEX": "St",
  "SUTRO HEIGHTS": "Ave",
  "SUTTER": "St",
  "SWEENY": "St",
  "SWISS": "Ave",
  "SYCAMORE": "St",
  "SYDNEY": "Way",
  "SYLVAN": "Dr",
  "TABER": "Pl",
  "TACOMA": "St",
  "TALBERT": "St",
  "TAMALPAIS": "Ter",
  "TAMPA": "Ln",
  "TAPIA": "Dr",
  "TARA": "St",
  "TARAVAL": "St",
  "TAYLOR": "St",
  "TEDDY": "Ave",
  "TEHAMA": "St",
  "TELEGRAPH": "Pl",
  "TELEGRAPH HILL": "Blvd",
  "TEMESCAL": "Ter",
  "TEMPLE": "St",
  "TENNESSEE": "St",
  "TERESITA": "Blvd",
  "TERRA VISTA": "Ave",
  "TERRY A FRANCOIS": "Blvd",
  "TEXAS": "St",
  "THERESA": "St",
  "THOMAS": "Ave",
  "THOMAS MELLON": "Dr",
  "THOMAS MORE": "Way",
  "THOR": "Ave",
  "THORNE": "Way",
  "THORNTON": "Ave",
  "THORP": "Ln",
  "THRIFT": "St",
  "TIFFANY": "Ave",
  "TIMOTHY PFLUEGER": "Pl",
  "TINGLEY": "St",
  "TIOGA": "Ave",
  "TOCOLOMA": "Ave",
  "TOLEDO": "Way",
  "TOMASO": "Ct",
  "TOMPKINS": "Ave",
  "TOPAZ": "Way",
  "TOPEKA": "Ave",
  "TORRENS": "Ct",
  "TOUCHARD": "St",
  "TOWERSIDE": "Ave",
  "TOWNSEND": "St",
  "TOYON": "Ln",
  "TRADER VIC": "Aly",
  "TRAINOR": "St",
  "TRANSVERSE": "Dr",
  "TREASURY": "Pl",
  "TREAT": "Ave",
  "TRENTON": "St",
  "TRINITY": "St",
  "TROY": "Aly",
  "TRUETT": "St",
  "TRUMBULL": "St",
  "TUBBS": "St",
  "TUCKER": "Ave",
  "TULANE": "St",
  "TUNNEL": "Ave",
  "TURK MURPHY": "Ln",
  "TURNER": "Ter",
  "TURQUOISE": "Way",
  "TUSCANY": "Aly",
  "TWIN PEAKS": "Blvd",
  "ULLOA": "St",
  "UNDERWOOD": "Ave",
  "UNION": "St",
  "UNITED NATIONS": "Plz",
  "UNIVERSITY": "St",
  "UPLAND": "Dr",
  "UPPER": "Ter",
  "URANUS": "Ter",
  "URBANO": "Dr",
  "UTAH": "St",
  "VALDEZ": "Ave",
  "VALENCIA": "St",
  "VALERTON": "Ct",
  "VALLEJO": "St",
  "VALLETTA": "Ct",
  "VALLEY": "St",
  "VALMAR": "Ter",
  "VALPARAISO": "St",
  "VAN BUREN": "St",
  "VAN DYKE": "Ave",
  "VAN NESS": "Ave",
  "VANDEWATER": "St",
  "VARA": "St",
  "VARELA": "Ave",
  "VARENNES": "St",
  "VARNEY": "Pl",
  "VASQUEZ": "Ave",
  "VASSAR": "Pl",
  "VEGA": "St",
  "VELASCO": "Ave",
  "VENARD": "Aly",
  "VENTURA": "Ave",
  "VENUS": "St",
  "VERDUN": "Way",
  "VERMONT": "St",
  "VERNA": "St",
  "VERNON": "St",
  "VESTA": "St",
  "VETERANS": "Dr",
  "VICENTE": "St",
  "VICHA RATANAPAKDEE": "Way",
  "VICKSBURG": "St",
  "VICTORIA": "St",
  "VIDAL": "Dr",
  "VIENNA": "St",
  "VILLA": "Ter",
  "VINE": "Ter",
  "VINTON": "Ct",
  "VIRGIL": "St",
  "VIRGINIA": "Ave",
  "VISITACION": "Ave",
  "VISTA": "Ln",
  "VISTA VERDE": "Ct",
  "VISTA VIEW": "Ct",
  "WABASH": "Ter",
  "WAGNER": "Aly",
  "WAITHMAN": "Way",
  "WALDO": "Aly",
  "WALL": "Pl",
  "WALLACE": "Ave",
  "WALLER": "St",
  "WALNUT": "St",
  "WALTER": "St",
  "WALTER U LUM": "Pl",
  "WALTHAM": "St",
  "WANDA": "St",
  "WARD": "St",
  "WARNER": "Pl",
  "WARREN": "Dr",
  "WARRIORS": "Way",
  "WASHBURN": "St",
  "WASHINGTON": "St",
  "WATCHMAN": "Way",
  "WATER": "St",
  "WATERFRONT": "St",
  "WATERLOO": "St",
  "WATERVILLE": "St",
  "WATT": "Ave",
  "WATTSON": "Pl",
  "WAVERLY": "Pl",
  "WAWONA": "St",
  "WAYLAND": "St",
  "WAYNE": "Pl",
  "WEBB": "Pl",
  "WEBSTER": "St",
  "WEDEMEYER": "St",
  "WELSH": "St",
  "WENTWORTH": "Pl",
  "WEST": "Rd",
  "WEST CLAY": "St",
  "WEST CRYSTAL COVE": "Ter",
  "WEST PACIFIC": "Ave",
  "WEST PORTAL": "Ave",
  "WEST VIEW": "Ave",
  "WESTBROOK": "Ct",
  "WESTERN SHORE": "Ln",
  "WESTGATE": "Dr",
  "WESTMOORLAND": "Dr",
  "WESTSIDE": "Dr",
  "WESTWOOD": "Dr",
  "WETMORE": "St",
  "WHEAT": "St",
  "WHEELER": "Ave",
  "WHIPPLE": "Ave",
  "WHITE": "St",
  "WHITECLIFF": "Way",
  "WHITING": "St",
  "WHITNEY": "St",
  "WHITNEY YOUNG": "Cir",
  "WHITTIER": "St",
  "WIESE": "St",
  "WILDE": "Ave",
  "WILDER": "St",
  "WILDWOOD": "Way",
  "WILLARD": "St",
  "WILLIAMS": "Ave",
  "WILLIAR": "Ave",
  "WILLIE B KENNEDY": "Dr",
  "WILLOW": "St",
  "WILMOT": "St",
  "WILSON": "St",
  "WINDING": "Way",
  "WINDSOR": "Pl",
  "WINFIELD": "St",
  "WINSTON": "Dr",
  "WINTER": "Pl",
  "WISCONSIN": "St",
  "WOOD": "St",
  "WOODACRE": "Dr",
  "WOODHAVEN": "Ct",
  "WOODLAND": "Ave",
  "WOODSIDE": "Ave",
  "WOODWARD": "St",
  "WOOL": "St",
  "WOOLSEY": "St",
  "WORCESTER": "Ave",
  "WORDEN": "St",
  "WORTH": "St",
  "WRIGHT": "St",
  "WYTON": "Ln",
  "YALE": "St",
  "YERBA BUENA": "Ave",
  "YORBA": "St",
  "YORK": "St",
  "YOSEMITE": "Ave",
  "YOUNG": "Ct",
  "YUKON": "St",
  "ZAMPA": "Ln",
  "ZIRCON": "Pl",
  "ZOE": "St",
  "ZOO": "Rd",
};

/**
 * Names the records write with more than one suffix, so a bare mention is genuinely
 * ambiguous. Numbered streets dominate this list because San Francisco has both a
 * `19th St` and a `19th Ave`.
 */
export const AMBIGUOUS_STREET_NAMES: readonly string[] = [
  "10th",
  "11th",
  "12th",
  "14th",
  "15th",
  "16th",
  "17th",
  "18th",
  "19th",
  "20th",
  "21st",
  "22nd",
  "23rd",
  "24th",
  "25th",
  "26th",
  "27th",
  "28th",
  "29th",
  "2nd",
  "30th",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
  "9th",
  "ACACIA",
  "BUENA VISTA",
  "CAMPUS",
  "CLOVER",
  "COVENTRY",
  "CROWN",
  "KEYES",
  "LINCOLN",
  "LUNADO",
  "MILLER",
  "MINT",
  "MISSION BAY",
  "ORD",
  "PALM",
  "PARK",
  "PORTAL",
  "PRESIDIO",
  "RALSTON",
  "RIDGE",
  "ROBINSON",
  "SHERIDAN",
  "TERRACE",
  "TURK"
];

/**
 * Named streets observed crossing the numbered *avenues* (the Richmond and Sunset grid).
 * This is how `19th and Irving` resolves to `19th Ave & Irving St` rather than `19th St`:
 * Irving crosses avenues, so its partner is an avenue.
 */
export const AVENUE_CROSS_STREETS: readonly string[] = [
  "ANZA",
  "BALBOA",
  "CABRILLO",
  "CALIFORNIA",
  "CLEMENT",
  "CORNWALL",
  "EL CAMINO DEL MAR",
  "EUCALYPTUS",
  "FULTON",
  "GEARY",
  "HUGO",
  "IRVING",
  "JOHN F KENNEDY",
  "JUDAH",
  "KIRKHAM",
  "LAKE",
  "LAWTON",
  "LINCOLN",
  "MORAGA",
  "NORIEGA",
  "OCEAN",
  "ORTEGA",
  "PACHECO",
  "POINT LOBOS",
  "QUINTARA",
  "RIVERA",
  "SANTIAGO",
  "SLOAT",
  "TARAVAL",
  "ULLOA",
  "VICENTE",
  "WAWONA",
  "YORBA"
];
